import { Link } from "react-router-dom";

const miscSite = () => {
  return (
    <div className="container">
      <div className="box">
        <hr />
        <h1>Data Creation Process</h1>
        <p>
          The data used on this Dark Souls Wiki was generated by exporting raw
          game data using
          <strong>
            {" "}
            <a href="https://github.com/soulsmods/DSMapStudio">DSMapStudio</a>
          </strong>
          , a powerful tool that allows you to inspect and manipulate the
          internal structure of Dark Souls games. This tool was essential for
          extracting detailed information about weapons, equipment, spells, and
          other game elements directly from the game files.
        </p>

        <h2>Step 1: Extracting Raw Data</h2>
        <p>
          Using{" "}
          <strong>
            <a href="https://github.com/soulsmods/DSMapStudio">DSMapStudio</a>
          </strong>
          , the raw data was exported from the game files. The tool provides
          access to various game parameters, including weapon stats, item
          descriptions, durability, weight, and much more. This raw data,
          however, was not in a format immediately suitable for a web-based
          Wiki.
        </p>

        <h2>Step 2: Cleaning and Processing with Python</h2>
        <p>
          Once the raw data was exported, Python was used to clean and transform
          the information into a usable format. This process involved:
        </p>
        <ul>
          <li>
            Parsing the exported files and organizing the data into categories
            such as weapons, spells, and items.
          </li>
          <li>Filtering out unnecessary or duplicate entries.</li>
          <li>
            Reformatting values into human-readable formats, such as converting
            internal IDs to meaningful descriptions and proper numerical
            formats.
          </li>
          <li>
            Ensuring the data matched the in-game representation accurately.
          </li>
        </ul>

        <h2>Step 3: Indexing for Web Usage</h2>
        <p>
          After cleaning, the data was structured and indexed to make it easy to
          search and display on the website. Python scripts were used to
          generate JSON files that the website could consume dynamically. This
          allows for fast access to weapon categories, detailed stats for each
          weapon, and the ability to cross-reference different types of
          equipment.
        </p>

        <h2>Data Usage on the Site</h2>

        <p>
          The website then consumes these JSON files to display the information
          to users. This allows the website to dynamically load the appropriate
          data when you visit various pages, such as viewing a weapon’s details
          or comparing items within a category. The indexing process ensures
          that the website operates efficiently and that content is easily
          retrievable.
        </p>
        <hr />
        <div className="Image-Loading">
          <h1>Image Loading from Texture Atlases</h1>
          <p>
            Images on this site are loaded using texture atlases, which are
            large images containing multiple smaller images packed together.
            This technique is essential for optimizing web performance, as it
            reduces the number of HTTP requests and allows for efficient use of
            memory. Each weapon or item in the game is associated with specific
            coordinates in the atlas, allowing for the extraction of the
            relevant images during rendering.
          </p>
          <h2>Tool for easily change sites pngs to atlases</h2>
          <p>
            To simplify the process of managing these atlas coordinates, I have
            developed a custom tool that enables easy copying and pasting of
            atlas locations. This tool significantly speeds up the workflow of
            linking images to their respective items by automating the retrieval
            of coordinates from the atlases.{" "}
            <Link to={`/atlas-exporter`}>See how it works Here</Link>
          </p>
          <p>
            The site utilizes the game's own texture atlases, ensuring that all
            images are accurate and reflective of the original game assets. By
            leveraging this method, we can provide a seamless and visually
            appealing experience for users browsing weapon and item details.
          </p>
        </div>
        <hr />
        <h1>Upcoming Features & Developement</h1>
        <div className="upcoming-features">
          <p>
            We are continuously working on enhancing the site with new features
            to improve user experience and provide more in-depth information.
            Here's a sneak peek at what’s coming:
          </p>

          <ul>
            <li>
              <strong>Additional Data Loading:</strong> Plan to load an
              additional file to enhance the weapon data presented on the site.
              This will allow for more comprehensive information, ensuring
              accuracy and depth in weapon stats.
            </li>

            <li>
              <strong>Expanded Content:</strong> Adding new content to various
              categories, including:
              <ul>
                <li>
                  <strong>Spells:</strong> In-game spells with detailed
                  descriptions and effects.
                </li>
                <li>
                  <strong>World:</strong> Lore that expands on the story and
                  setting of the game.
                </li>
                <li>
                  <strong>Information:</strong> A deeper dive into the game
                  mechanics.
                </li>
                <li>
                  <strong>Characters:</strong> Exploring the NPCs and their
                  lore, providing background and story details.
                </li>
              </ul>
            </li>

            <li>
              <strong>Chat & Feedback Box:</strong> I am developing a feedback
              box that allows for one-way communication, where users can report
              issues or provide suggestions. This feature will help us respond
              quickly to user-reported bugs and improvements.
            </li>
          </ul>

          <p>Stay tuned for these updates as i continue to improve the site!</p>
        </div>
      </div>
    </div>
  );
};
export default miscSite;
