const miscSite = () => {
  return (
    <div className="container">
      <div className="box">
        <h1>Data Creation Process</h1>
        <p>
          The data used on this Dark Souls Wiki was generated by exporting raw
          game data using
          <strong> DSMapStudio</strong>, a powerful tool that allows you to
          inspect and manipulate the internal structure of Dark Souls games.
          This tool was essential for extracting detailed information about
          weapons, equipment, spells, and other game elements directly from the
          game files.
        </p>

        <h2>Step 1: Extracting Raw Data</h2>
        <p>
          Using <strong>DSMapStudio</strong>, the raw data was exported from the
          game files. The tool provides access to various game parameters,
          including weapon stats, item descriptions, durability, weight, and
          much more. This raw data, however, was not in a format immediately
          suitable for a web-based Wiki.
        </p>

        <h2>Step 2: Cleaning and Processing with Python</h2>
        <p>
          Once the raw data was exported, Python was used to clean and transform
          the information into a usable format. This process involved:
        </p>
        <ul>
          <li>
            Parsing the exported files and organizing the data into categories
            such as weapons, spells, and items.
          </li>
          <li>Filtering out unnecessary or duplicate entries.</li>
          <li>
            Reformatting values into human-readable formats, such as converting
            internal IDs to meaningful descriptions and proper numerical
            formats.
          </li>
          <li>
            Ensuring the data matched the in-game representation accurately.
          </li>
        </ul>

        <h2>Step 3: Indexing for Web Usage</h2>
        <p>
          After cleaning, the data was structured and indexed to make it easy to
          search and display on the website. Python scripts were used to
          generate JSON files that the website could consume dynamically. This
          allows for fast access to weapon categories, detailed stats for each
          weapon, and the ability to cross-reference different types of
          equipment.
        </p>

        <h2>Data Usage on the Site</h2>
        <p>
          The website then consumes these JSON files to display the information
          to users. This allows the website to dynamically load the appropriate
          data when you visit various pages, such as viewing a weapon’s details
          or comparing items within a category. The indexing process ensures
          that the website operates efficiently and that content is easily
          retrievable.
        </p>

        <h2>Contributing to the Wiki</h2>
        <p>
          This project is open source, so anyone who wishes to contribute to the
          development of the Wiki can do so via the GitHub repository linked in
          the footer. New contributions could include adding more detailed
          information, fixing any inaccuracies, or even expanding the site's
          scope.
        </p>

        <p>
          In summary, this website stands as a community-driven resource created
          by extracting data from the game itself, cleaned and organized with
          Python, and indexed for easy web-based access. With DSMapStudio and
          Python, we've ensured that the data presented here is accurate,
          comprehensive, and easily accessible for Dark Souls fans.
        </p>
      </div>
    </div>
  );
};
export default miscSite;
